-- The Taste Restaurant OS - safe public launch schema
-- Scope: one restaurant, default store_id = the-taste
-- Safe to run on an existing project. This file does not drop production data.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS menu_categories (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  name VARCHAR(100) NOT NULL,
  icon VARCHAR(50) DEFAULT '',
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS menu_items (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  category_id BIGINT REFERENCES menu_categories(id) ON DELETE SET NULL,
  name VARCHAR(100) NOT NULL,
  price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  is_available BOOLEAN DEFAULT TRUE,
  is_veg BOOLEAN DEFAULT TRUE,
  sort_order INT DEFAULT 0,
  image_url VARCHAR(500) DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  client_order_id UUID,
  idempotency_key TEXT,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  display_token VARCHAR(20),
  type VARCHAR(20) DEFAULT 'takeaway',
  status VARCHAR(20) DEFAULT 'pending',
  channel VARCHAR(20) DEFAULT 'pos',
  source VARCHAR(20) DEFAULT 'pos',
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  subtotal NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  tax NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  tax_percent NUMERIC(5, 2) DEFAULT 0.00,
  delivery_fee NUMERIC(10, 2) DEFAULT 0.00,
  total NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  payment_method VARCHAR(20),
  payment_status VARCHAR(20) DEFAULT 'unpaid',
  payment_reference TEXT DEFAULT '',
  payment_verified_at TIMESTAMPTZ,
  payment_verified_by TEXT DEFAULT '',
  payment_collected_at TIMESTAMPTZ,
  customer_name VARCHAR(100) DEFAULT '',
  customer_phone VARCHAR(20) DEFAULT '',
  delivery_address TEXT DEFAULT '',
  delivery_landmark TEXT DEFAULT '',
  delivery_notes TEXT DEFAULT '',
  delivery_status VARCHAR(30) DEFAULT 'none',
  delivery_staff_id BIGINT,
  delivery_staff_name VARCHAR(100) DEFAULT '',
  delivery_assigned_at TIMESTAMPTZ,
  delivery_out_at TIMESTAMPTZ,
  delivered_at TIMESTAMPTZ,
  auth_user_id UUID,
  staff_id BIGINT,
  staff_name VARCHAR(100) DEFAULT '',
  table_id BIGINT,
  notes TEXT DEFAULT '',
  requires_server_validation BOOLEAN DEFAULT FALSE,
  validation_status VARCHAR(30) DEFAULT 'trusted_staff',
  sync_attempts INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  completed_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS tables (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  number INT NOT NULL,
  capacity INT DEFAULT 2,
  floor_section VARCHAR(50) DEFAULT 'Main',
  status VARCHAR(20) DEFAULT 'available',
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  name VARCHAR(100) NOT NULL,
  quantity NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
  min_threshold NUMERIC(10, 2) DEFAULT 0.00,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS suppliers (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  name VARCHAR(100) NOT NULL,
  contact VARCHAR(150) DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS staff (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  auth_user_id UUID,
  name VARCHAR(100) NOT NULL,
  role VARCHAR(30) NOT NULL CHECK (role IN ('developer', 'owner', 'manager', 'cashier', 'kitchen', 'waiter', 'delivery')),
  pin_hash VARCHAR(64) NOT NULL,
  allow_express BOOLEAN DEFAULT FALSE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS staff_memberships (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
  auth_user_id UUID NOT NULL,
  role VARCHAR(30) NOT NULL CHECK (role IN ('developer', 'owner', 'manager', 'cashier', 'kitchen', 'waiter', 'delivery')),
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (store_id, auth_user_id)
);

CREATE TABLE IF NOT EXISTS shifts (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  staff_id BIGINT REFERENCES staff(id) ON DELETE CASCADE,
  clock_in VARCHAR(50),
  clock_out VARCHAR(50),
  date VARCHAR(30),
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS activity_log (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  timestamp TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  action VARCHAR(150) NOT NULL,
  staff_name VARCHAR(100) DEFAULT 'System',
  details TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS audit_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  actor_staff_id BIGINT,
  actor_auth_user_id UUID,
  action TEXT NOT NULL,
  target_table TEXT,
  target_id TEXT,
  details JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS customers (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  auth_user_id UUID,
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  birthday VARCHAR(30),
  total_spent NUMERIC(10, 2) DEFAULT 0.00,
  visit_count INT DEFAULT 0,
  loyalty_points INT DEFAULT 0,
  tier VARCHAR(20) DEFAULT 'bronze',
  last_visit TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE (store_id, phone)
);

CREATE TABLE IF NOT EXISTS public_order_rate_limits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  ip_hash TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS client_order_id UUID;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS idempotency_key TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS display_token VARCHAR(20);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS requires_server_validation BOOLEAN DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS validation_status VARCHAR(30) DEFAULT 'trusted_staff';
ALTER TABLE staff ADD COLUMN IF NOT EXISTS auth_user_id UUID;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS allow_express BOOLEAN DEFAULT FALSE;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS image_url VARCHAR(500) DEFAULT '';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS auth_user_id UUID;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS auth_user_id UUID;

UPDATE orders SET client_order_id = gen_random_uuid() WHERE client_order_id IS NULL;
UPDATE orders SET idempotency_key = client_order_id::text WHERE idempotency_key IS NULL;
UPDATE orders SET display_token = split_part(order_number, '-', array_length(string_to_array(order_number, '-'), 1)) WHERE display_token IS NULL;

ALTER TABLE orders ALTER COLUMN client_order_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN idempotency_key SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_client_order_id ON orders(store_id, client_order_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_idempotency_key ON orders(store_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_menu_items_category_available ON menu_items(store_id, category_id, is_available);
CREATE INDEX IF NOT EXISTS idx_orders_store_created ON orders(store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_delivery ON orders(store_id, type, delivery_status);
CREATE INDEX IF NOT EXISTS idx_staff_memberships_auth ON staff_memberships(store_id, auth_user_id) WHERE is_active = TRUE;
CREATE INDEX IF NOT EXISTS idx_rate_limits_window ON public_order_rate_limits(store_id, ip_hash, created_at DESC);

ALTER TABLE menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE tables ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff ENABLE ROW LEVEL SECURITY;
ALTER TABLE staff_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
ALTER TABLE activity_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public_order_rate_limits ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON menu_categories, menu_items TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON menu_categories, menu_items, tables, suppliers, staff, staff_memberships, shifts TO authenticated;
GRANT SELECT, INSERT, UPDATE ON orders, inventory, customers TO authenticated;
GRANT SELECT, INSERT ON activity_log, audit_events TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

DROP POLICY IF EXISTS "public active menu categories read" ON menu_categories;
CREATE POLICY "public active menu categories read" ON menu_categories
  FOR SELECT TO anon, authenticated
  USING (is_active = TRUE);

DROP POLICY IF EXISTS "public available menu items read" ON menu_items;
CREATE POLICY "public available menu items read" ON menu_items
  FOR SELECT TO anon, authenticated
  USING (is_available = TRUE);

DROP POLICY IF EXISTS "staff memberships self read" ON staff_memberships;
CREATE POLICY "staff memberships self read" ON staff_memberships
  FOR SELECT TO authenticated
  USING (auth_user_id = (SELECT auth.uid()) AND is_active = TRUE);

DROP POLICY IF EXISTS "staff access menu_categories" ON menu_categories;
CREATE POLICY "staff access menu_categories" ON menu_categories
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = menu_categories.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = menu_categories.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access menu_items" ON menu_items;
CREATE POLICY "staff access menu_items" ON menu_items
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = menu_items.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = menu_items.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access orders" ON orders;
CREATE POLICY "staff access orders" ON orders
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = orders.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = orders.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access tables" ON tables;
CREATE POLICY "staff access tables" ON tables
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = tables.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = tables.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access inventory" ON inventory;
CREATE POLICY "staff access inventory" ON inventory
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = inventory.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = inventory.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access suppliers" ON suppliers;
CREATE POLICY "staff access suppliers" ON suppliers
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = suppliers.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = suppliers.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access staff" ON staff;
CREATE POLICY "staff access staff" ON staff
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = staff.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = staff.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access shifts" ON shifts;
CREATE POLICY "staff access shifts" ON shifts
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = shifts.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = shifts.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access activity_log" ON activity_log;
CREATE POLICY "staff access activity_log" ON activity_log
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = activity_log.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = activity_log.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access audit_events" ON audit_events;
CREATE POLICY "staff access audit_events" ON audit_events
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = audit_events.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

DROP POLICY IF EXISTS "staff access customers" ON customers;
CREATE POLICY "staff access customers" ON customers
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = customers.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = customers.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

-- Customer Self Profile Policy
DROP POLICY IF EXISTS "customer self read write" ON customers;
CREATE POLICY "customer self read write" ON customers
  FOR ALL TO authenticated
  USING (auth_user_id = (SELECT auth.uid()))
  WITH CHECK (auth_user_id = (SELECT auth.uid()));

-- Customer Own Orders Read Policy
DROP POLICY IF EXISTS "customer read own orders" ON orders;
CREATE POLICY "customer read own orders" ON orders
  FOR SELECT TO authenticated
  USING (
    customer_phone = (SELECT phone FROM customers WHERE auth_user_id = (SELECT auth.uid()) LIMIT 1)
    OR auth_user_id = (SELECT auth.uid())
  );

-- Customer Own Orders Insert Policy
DROP POLICY IF EXISTS "customer insert own orders" ON orders;
CREATE POLICY "customer insert own orders" ON orders
  FOR INSERT TO authenticated
  WITH CHECK (auth_user_id = (SELECT auth.uid()));

-- Create storage bucket for menu images
INSERT INTO storage.buckets (id, name, public)
VALUES ('menu-images', 'menu-images', true)
ON CONFLICT (id) DO NOTHING;

-- RLS policies for storage bucket
DROP POLICY IF EXISTS "Allow public read access to menu images" ON storage.objects;
CREATE POLICY "Allow public read access to menu images" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'menu-images');

DROP POLICY IF EXISTS "Allow staff to manage menu images" ON storage.objects;
CREATE POLICY "Allow staff to manage menu images" ON storage.objects
  FOR ALL TO authenticated
  USING (bucket_id = 'menu-images')
  WITH CHECK (bucket_id = 'menu-images');

DO $$
DECLARE
  table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['menu_categories','menu_items','orders','tables','inventory','suppliers','staff','staff_memberships','shifts','activity_log','customers']
  LOOP
    BEGIN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE %I', table_name);
    EXCEPTION
      WHEN duplicate_object THEN NULL;
      WHEN undefined_object THEN NULL;
    END;
  END LOOP;
END $$;

-- ── Ledger Immutability & Audit Triggers ──

-- Prevent any UPDATE or DELETE on activity_log and audit_events
CREATE OR REPLACE FUNCTION prevent_modification()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Data in this table is immutable and cannot be updated or deleted.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_mod_activity_log ON activity_log;
CREATE TRIGGER trg_prevent_mod_activity_log
  BEFORE UPDATE OR DELETE ON activity_log
  FOR EACH ROW
  EXECUTE FUNCTION prevent_modification();

DROP TRIGGER IF EXISTS trg_prevent_mod_audit_events ON audit_events;
CREATE TRIGGER trg_prevent_mod_audit_events
  BEFORE UPDATE OR DELETE ON audit_events
  FOR EACH ROW
  EXECUTE FUNCTION prevent_modification();

-- Prevent deletion of orders
CREATE OR REPLACE FUNCTION prevent_order_deletion()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'Orders cannot be deleted once created. Use order status cancellation instead.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_delete_orders ON orders;
CREATE TRIGGER trg_prevent_delete_orders
  BEFORE DELETE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION prevent_order_deletion();

-- Log order status/total changes to audit_events
CREATE OR REPLACE FUNCTION audit_order_changes()
RETURNS TRIGGER AS $$
DECLARE
  change_details JSONB;
BEGIN
  -- Only log if there was a meaningful change
  IF OLD.status IS DISTINCT FROM NEW.status OR 
     OLD.payment_status IS DISTINCT FROM NEW.payment_status OR 
     OLD.total IS DISTINCT FROM NEW.total THEN
     
     change_details := jsonb_build_object(
       'old_status', OLD.status,
       'new_status', NEW.status,
       'old_payment_status', OLD.payment_status,
       'new_payment_status', NEW.payment_status,
       'old_total', OLD.total::text,
       'new_total', NEW.total::text
     );
     
     INSERT INTO audit_events (store_id, actor_staff_id, actor_auth_user_id, action, target_table, target_id, details)
     VALUES (
       NEW.store_id,
       NEW.staff_id,
       NEW.auth_user_id,
       'order_update',
       'orders',
       NEW.id::text,
       change_details
     );
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_audit_order_changes ON orders;
CREATE TRIGGER trg_audit_order_changes
  AFTER UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION audit_order_changes();

-- ── Recipes Cloud Setup ──
CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT PRIMARY KEY,
  store_id TEXT NOT NULL DEFAULT 'the-taste',
  menu_item_id BIGINT REFERENCES menu_items(id) ON DELETE CASCADE,
  ingredients JSONB NOT NULL DEFAULT '[]'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT, UPDATE, DELETE ON recipes TO authenticated;

DROP POLICY IF EXISTS "staff access recipes" ON recipes;
CREATE POLICY "staff access recipes" ON recipes
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = recipes.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE))
  WITH CHECK (EXISTS (SELECT 1 FROM staff_memberships sm WHERE sm.store_id = recipes.store_id AND sm.auth_user_id = (SELECT auth.uid()) AND sm.is_active = TRUE));

-- ── Secure Stripe Webhook Emulation RPC ──
CREATE OR REPLACE FUNCTION emulate_stripe_webhook(
  order_client_id UUID,
  payment_intent_id TEXT,
  status TEXT
)
RETURNS BOOLEAN AS $$
BEGIN
  IF status = 'succeeded' THEN
    UPDATE orders
    SET payment_status = 'paid',
        payment_reference = payment_intent_id,
        payment_verified_at = NOW(),
        updated_at = NOW()
    WHERE client_order_id = order_client_id;
    
    RETURN TRUE;
  END IF;
  RETURN FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ── Cloud Inventory Auto-Deduction Trigger ──
CREATE OR REPLACE FUNCTION deduct_inventory_on_order()
RETURNS TRIGGER AS $$
DECLARE
  order_item RECORD;
  recipe_ingredient RECORD;
  recipe_rec RECORD;
  inv_match_id BIGINT;
  deduct_qty NUMERIC;
BEGIN
  -- Process each item in the order
  FOR order_item IN 
    SELECT * FROM jsonb_to_recordset(NEW.items) AS x(itemId BIGINT, itemName TEXT, quantity INT)
  LOOP
    -- Look for a recipe on the server
    SELECT * INTO recipe_rec FROM recipes WHERE menu_item_id = order_item.itemId LIMIT 1;
    
    IF recipe_rec.id IS NOT NULL THEN
      -- Loop through recipe ingredients
      FOR recipe_ingredient IN 
        SELECT * FROM jsonb_to_recordset(recipe_rec.ingredients) AS y(inventoryId BIGINT, quantity NUMERIC)
      LOOP
        deduct_qty := COALESCE(recipe_ingredient.quantity, 0) * COALESCE(order_item.quantity, 1);
        UPDATE inventory 
        SET quantity = GREATEST(0, quantity - deduct_qty),
            updated_at = NOW()
        WHERE id = recipe_ingredient.inventoryId AND store_id = NEW.store_id;
      END LOOP;
    ELSE
      -- Fallback: Fuzzy name match against inventory table
      SELECT id INTO inv_match_id 
      FROM inventory 
      WHERE store_id = NEW.store_id 
        AND (LOWER(TRIM(name)) = LOWER(TRIM(order_item.itemName)) 
             OR LOWER(TRIM(name)) LIKE '%' || LOWER(TRIM(order_item.itemName)) || '%'
             OR LOWER(TRIM(order_item.itemName)) LIKE '%' || LOWER(TRIM(name)) || '%')
      LIMIT 1;
      
      IF inv_match_id IS NOT NULL THEN
        UPDATE inventory 
        SET quantity = GREATEST(0, quantity - COALESCE(order_item.quantity, 1)),
            updated_at = NOW()
        WHERE id = inv_match_id AND store_id = NEW.store_id;
      END IF;
    END IF;
  END LOOP;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_deduct_inventory_on_order ON orders;
CREATE TRIGGER trg_deduct_inventory_on_order
  AFTER INSERT ON orders
  FOR EACH ROW
  EXECUTE FUNCTION deduct_inventory_on_order();
