-- Fix orders table id column auto-incrementing identity sequence
ALTER TABLE public.orders ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Resync sequence to the maximum existing order ID to prevent primary key conflicts
SELECT setval(pg_get_serial_sequence('public.orders', 'id'), COALESCE(MAX(id), 1)) FROM public.orders;
