-- Reproducible base schema for The Taste Restaurant OS.
-- This migration predates all feature and security migrations in this folder.

create extension if not exists pgcrypto;
create extension if not exists vector;

create table if not exists public.menu_categories (
  id bigint primary key,
  store_id text not null default 'the-taste',
  name varchar(100) not null,
  icon varchar(50) not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint primary key,
  store_id text not null default 'the-taste',
  category_id bigint references public.menu_categories(id) on delete set null,
  name varchar(100) not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  is_available boolean not null default true,
  is_veg boolean not null default true,
  sort_order integer not null default 0,
  image_url varchar(500) not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.tables (
  id bigint primary key,
  store_id text not null default 'the-taste',
  number integer not null,
  capacity integer not null default 2 check (capacity > 0),
  floor_section varchar(50) not null default 'Main',
  status varchar(20) not null default 'available',
  updated_at timestamptz not null default now(),
  unique (store_id, number)
);

create table if not exists public.staff (
  id bigint primary key,
  store_id text not null default 'the-taste',
  auth_user_id uuid references auth.users(id) on delete set null,
  name varchar(100) not null,
  role varchar(30) not null check (role in ('developer','owner','manager','cashier','kitchen','waiter','delivery')),
  pin_hash varchar(64), -- deprecated; never granted to browser clients
  allow_express boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, auth_user_id)
);

create table if not exists public.staff_memberships (
  id bigint generated by default as identity primary key,
  store_id text not null default 'the-taste',
  staff_id bigint references public.staff(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role varchar(30) not null check (role in ('developer','owner','manager','cashier','kitchen','waiter','delivery')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, auth_user_id)
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  store_id text not null default 'the-taste',
  client_order_id uuid not null default gen_random_uuid(),
  idempotency_key text not null default gen_random_uuid()::text,
  order_number varchar(50) not null,
  display_token varchar(20),
  type varchar(20) not null default 'takeaway',
  status varchar(20) not null default 'pending',
  channel varchar(20) not null default 'pos',
  source varchar(20) not null default 'pos',
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  tax_percent numeric(5,2) not null default 0,
  delivery_fee numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  payment_method varchar(20),
  payment_status varchar(20) not null default 'unpaid',
  payment_reference text not null default '',
  payment_verified_at timestamptz,
  payment_verified_by text not null default '',
  payment_collected_at timestamptz,
  customer_name varchar(100) not null default '',
  customer_phone varchar(20) not null default '',
  delivery_address text not null default '',
  delivery_landmark text not null default '',
  delivery_notes text not null default '',
  delivery_status varchar(30) not null default 'none',
  delivery_staff_id bigint references public.staff(id) on delete set null,
  delivery_staff_name varchar(100) not null default '',
  delivery_assigned_at timestamptz,
  delivery_out_at timestamptz,
  delivered_at timestamptz,
  auth_user_id uuid references auth.users(id) on delete set null,
  staff_id bigint references public.staff(id) on delete set null,
  staff_name varchar(100) not null default '',
  table_id bigint references public.tables(id) on delete set null,
  notes text not null default '',
  requires_server_validation boolean not null default false,
  validation_status varchar(30) not null default 'trusted_staff',
  sync_attempts integer not null default 0,
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (store_id, client_order_id),
  unique (store_id, idempotency_key),
  unique (store_id, order_number)
);

create table if not exists public.inventory (
  id bigint primary key,
  store_id text not null default 'the-taste',
  name varchar(100) not null,
  quantity numeric(12,3) not null default 0,
  min_threshold numeric(12,3) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint primary key,
  store_id text not null default 'the-taste',
  name varchar(100) not null,
  contact varchar(150) not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.shifts (
  id bigint primary key,
  store_id text not null default 'the-taste',
  staff_id bigint references public.staff(id) on delete cascade,
  clock_in varchar(50),
  clock_out varchar(50),
  date varchar(30),
  updated_at timestamptz not null default now()
);

create table if not exists public.activity_log (
  id bigint primary key,
  store_id text not null default 'the-taste',
  timestamp timestamptz not null default now(),
  action varchar(150) not null,
  staff_name varchar(100) not null default 'System',
  details text not null default ''
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  store_id text not null default 'the-taste',
  actor_staff_id bigint,
  actor_auth_user_id uuid,
  action text not null,
  target_table text,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id bigint primary key,
  store_id text not null default 'the-taste',
  auth_user_id uuid references auth.users(id) on delete set null,
  name varchar(100) not null,
  phone varchar(20) not null,
  birthday varchar(30),
  total_spent numeric(12,2) not null default 0,
  visit_count integer not null default 0,
  loyalty_points integer not null default 0,
  tier varchar(20) not null default 'bronze',
  last_visit timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (store_id, phone)
);

create table if not exists public.recipes (
  id bigint primary key,
  store_id text not null default 'the-taste',
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  ingredients jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  unique (store_id, menu_item_id)
);

create table if not exists public.public_order_rate_limits (
  id bigint generated by default as identity primary key,
  store_id text not null default 'the-taste',
  ip_hash text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.document_embeddings (
  id uuid primary key default gen_random_uuid(),
  store_id text not null default 'the-taste',
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(384) not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_menu_items_category_available on public.menu_items(store_id, category_id, is_available);
create index if not exists idx_orders_store_created on public.orders(store_id, created_at desc);
create index if not exists idx_orders_delivery on public.orders(store_id, type, delivery_status);
create index if not exists idx_staff_memberships_auth on public.staff_memberships(store_id, auth_user_id) where is_active;
create index if not exists idx_public_order_rate_limits_window on public.public_order_rate_limits(store_id, ip_hash, created_at desc);
create index if not exists idx_document_embeddings_hnsw on public.document_embeddings using hnsw (embedding vector_cosine_ops);

alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.tables enable row level security;
alter table public.staff enable row level security;
alter table public.staff_memberships enable row level security;
alter table public.orders enable row level security;
alter table public.inventory enable row level security;
alter table public.suppliers enable row level security;
alter table public.shifts enable row level security;
alter table public.activity_log enable row level security;
alter table public.audit_events enable row level security;
alter table public.customers enable row level security;
alter table public.recipes enable row level security;
alter table public.public_order_rate_limits enable row level security;
alter table public.document_embeddings enable row level security;

grant usage on schema public to anon, authenticated;
grant select on public.menu_categories, public.menu_items, public.tables to anon, authenticated;
grant select, insert, update, delete on public.menu_categories, public.menu_items, public.tables, public.suppliers, public.staff, public.staff_memberships, public.shifts, public.recipes to authenticated;
grant select, insert, update on public.orders, public.inventory, public.customers to authenticated;
grant select, insert on public.activity_log, public.audit_events to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "public active menu categories read" on public.menu_categories;
create policy "public active menu categories read" on public.menu_categories
  for select to anon, authenticated using (is_active);
drop policy if exists "public available menu items read" on public.menu_items;
create policy "public available menu items read" on public.menu_items
  for select to anon, authenticated using (is_available);
drop policy if exists "public read tables" on public.tables;
create policy "public read tables" on public.tables
  for select to anon, authenticated using (true);
drop policy if exists "staff memberships self read" on public.staff_memberships;
create policy "staff memberships self read" on public.staff_memberships
  for select to authenticated using (auth_user_id = (select auth.uid()) and is_active);

drop policy if exists "staff access menu_categories" on public.menu_categories;
create policy "staff access menu_categories" on public.menu_categories for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_categories.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_categories.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access menu_items" on public.menu_items;
create policy "staff access menu_items" on public.menu_items for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_items.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = menu_items.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access orders" on public.orders;
create policy "staff access orders" on public.orders for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = orders.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = orders.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access tables" on public.tables;
create policy "staff access tables" on public.tables for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = tables.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = tables.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access inventory" on public.inventory;
create policy "staff access inventory" on public.inventory for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = inventory.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = inventory.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access suppliers" on public.suppliers;
create policy "staff access suppliers" on public.suppliers for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = suppliers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = suppliers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access staff" on public.staff;
create policy "staff access staff" on public.staff for select to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = staff.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access shifts" on public.shifts;
create policy "staff access shifts" on public.shifts for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = shifts.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = shifts.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access activity_log" on public.activity_log;
create policy "staff access activity_log" on public.activity_log for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = activity_log.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = activity_log.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access audit_events" on public.audit_events;
create policy "staff access audit_events" on public.audit_events for select to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = audit_events.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access customers" on public.customers;
create policy "staff access customers" on public.customers for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = customers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = customers.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "staff access recipes" on public.recipes;
create policy "staff access recipes" on public.recipes for all to authenticated
  using (exists (select 1 from public.staff_memberships sm where sm.store_id = recipes.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (exists (select 1 from public.staff_memberships sm where sm.store_id = recipes.store_id and sm.auth_user_id = (select auth.uid()) and sm.is_active));
drop policy if exists "customer self read write" on public.customers;
create policy "customer self read write" on public.customers for all to authenticated
  using (auth_user_id = (select auth.uid())) with check (auth_user_id = (select auth.uid()));
drop policy if exists "customer read own orders" on public.orders;
create policy "customer read own orders" on public.orders for select to authenticated
  using (auth_user_id = (select auth.uid()));

create or replace function public.consume_public_order_attempt(target_store_id text, target_ip_hash text, max_attempts integer, window_minutes integer)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare attempt_count integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(target_store_id || ':' || target_ip_hash, 0));
  delete from public.public_order_rate_limits where created_at < now() - make_interval(mins => window_minutes);
  select count(*) into attempt_count from public.public_order_rate_limits
    where store_id = target_store_id and ip_hash = target_ip_hash and created_at >= now() - make_interval(mins => window_minutes);
  if attempt_count >= max_attempts then return false; end if;
  insert into public.public_order_rate_limits(store_id, ip_hash) values (target_store_id, target_ip_hash);
  return true;
end
$$;
revoke all on function public.consume_public_order_attempt(text, text, integer, integer) from public, anon, authenticated;
grant execute on function public.consume_public_order_attempt(text, text, integer, integer) to service_role;

-- Kept only so the historical remediation migration can revoke it; the final
-- launch hardening migration removes this obsolete mock-payment function.
create or replace function public.emulate_stripe_webhook(order_client_id uuid, payment_intent_id text, status text)
returns boolean
language sql
security definer
set search_path = ''
as $$ select false $$;
revoke all on function public.emulate_stripe_webhook(uuid, text, text) from public, anon, authenticated;

create or replace function public.match_documents(query_embedding vector(384), match_threshold float, match_count integer, filter_store_id text)
returns table (id uuid, content text, metadata jsonb, similarity float)
language sql
stable
security definer
set search_path = ''
as $$
  select d.id, d.content, d.metadata, (1 - (d.embedding <=> query_embedding))::float
  from public.document_embeddings d
  where d.store_id = filter_store_id and 1 - (d.embedding <=> query_embedding) > match_threshold
  order by d.embedding <=> query_embedding
  limit least(greatest(match_count, 1), 20)
$$;
revoke all on function public.match_documents(vector, float, integer, text) from public, anon, authenticated;
grant execute on function public.match_documents(vector, float, integer, text) to service_role;

create or replace function public.prevent_ledger_modification()
returns trigger language plpgsql set search_path = '' as $$
begin raise exception 'Ledger records are immutable'; end
$$;
drop trigger if exists trg_prevent_mod_activity_log on public.activity_log;
create trigger trg_prevent_mod_activity_log before update or delete on public.activity_log
  for each row execute function public.prevent_ledger_modification();
drop trigger if exists trg_prevent_mod_audit_events on public.audit_events;
create trigger trg_prevent_mod_audit_events before update or delete on public.audit_events
  for each row execute function public.prevent_ledger_modification();

create or replace function public.prevent_order_deletion()
returns trigger language plpgsql set search_path = '' as $$
begin raise exception 'Orders cannot be deleted; cancel the order instead'; end
$$;
drop trigger if exists trg_prevent_delete_orders on public.orders;
create trigger trg_prevent_delete_orders before delete on public.orders
  for each row execute function public.prevent_order_deletion();

insert into storage.buckets (id, name, public)
values ('menu-images', 'menu-images', true)
on conflict (id) do update set public = excluded.public;
drop policy if exists "Allow public read access to menu images" on storage.objects;
create policy "Allow public read access to menu images" on storage.objects
  for select to anon, authenticated using (bucket_id = 'menu-images');
drop policy if exists "Allow staff to manage menu images" on storage.objects;
create policy "Allow staff to manage menu images" on storage.objects
  for all to authenticated
  using (bucket_id = 'menu-images' and exists (select 1 from public.staff_memberships sm where sm.auth_user_id = (select auth.uid()) and sm.is_active))
  with check (bucket_id = 'menu-images' and exists (select 1 from public.staff_memberships sm where sm.auth_user_id = (select auth.uid()) and sm.is_active));

do $$
declare table_name text;
begin
  foreach table_name in array array['menu_categories','menu_items','orders','tables','inventory','suppliers','staff','staff_memberships','shifts','activity_log','customers','recipes']
  loop
    begin
      execute format('alter publication supabase_realtime add table %I', table_name);
    exception when duplicate_object then null; when undefined_object then null;
    end;
  end loop;
end
$$;
