-- Fix orders table id column auto-incrementing identity sequence
ALTER TABLE public.orders ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Resync sequence to the maximum existing order ID to prevent primary key conflicts
SELECT setval(pg_get_serial_sequence('public.orders', 'id'), COALESCE(MAX(id), 1)) FROM public.orders;

-- Create trigger function to automatically sync sequence on explicit ID inserts
CREATE OR REPLACE FUNCTION public.sync_orders_id_sequence()
RETURNS TRIGGER AS $$
DECLARE
  seq_name TEXT;
  curr_val BIGINT;
BEGIN
  IF NEW.id IS NOT NULL THEN
    seq_name := pg_get_serial_sequence('public.orders', 'id');
    IF seq_name IS NOT NULL THEN
      EXECUTE format('SELECT last_value FROM %s', seq_name) INTO curr_val;
      IF NEW.id > curr_val THEN
        EXECUTE format('SELECT setval(%L, %s)', seq_name, NEW.id);
      END IF;
    END IF;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Bind trigger to the orders table
DROP TRIGGER IF EXISTS trg_sync_orders_id_sequence ON public.orders;
CREATE TRIGGER trg_sync_orders_id_sequence
  BEFORE INSERT ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.sync_orders_id_sequence();

