-- Per-dish descriptions and paid add-ons.
--
-- The storefront had no place to put real dish copy, so every item rendered the
-- same fabricated sentence, and the "extra cheese" option in the customer app
-- was hardcoded in the component rather than being data an owner controls.
--
-- Add-on prices are charged, so they are validated and priced server-side in
-- the public-order Edge Function exactly like the dish price itself: the client
-- sends which add-ons were chosen, never what they cost.

-- ── Descriptions ────────────────────────────────────────────────
alter table public.menu_items
  add column if not exists description text not null default '';

-- ── Add-ons ─────────────────────────────────────────────────────
create table if not exists public.menu_item_addons (
  id bigint generated by default as identity primary key,
  store_id text not null default 'the-taste',
  menu_item_id bigint not null references public.menu_items(id) on delete cascade,
  name varchar(60) not null,
  price numeric(12,2) not null default 0 check (price >= 0),
  is_active boolean not null default true,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now(),
  unique (store_id, menu_item_id, name)
);

-- The customer app reads a dish's add-ons by dish; the manager screen lists
-- them per store. Both are covered by this index.
create index if not exists menu_item_addons_store_item_idx
  on public.menu_item_addons (store_id, menu_item_id, sort_order);

alter table public.menu_item_addons enable row level security;

grant select on table public.menu_item_addons to anon, authenticated;
grant insert, update, delete on table public.menu_item_addons to authenticated;

-- A customer may only see add-ons that are on offer, mirroring how
-- `is_available` gates the dish itself.
drop policy if exists "public active menu addons read" on public.menu_item_addons;
create policy "public active menu addons read" on public.menu_item_addons
  for select to anon, authenticated using (is_active);

drop policy if exists "staff read menu_item_addons" on public.menu_item_addons;
create policy "staff read menu_item_addons" on public.menu_item_addons
  for select to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager','cashier','kitchen','waiter','delivery']));

drop policy if exists "managers write menu_item_addons" on public.menu_item_addons;
create policy "managers write menu_item_addons" on public.menu_item_addons
  for all to authenticated
  using (public.has_staff_role(store_id, array['developer','owner','manager']))
  with check (public.has_staff_role(store_id, array['developer','owner','manager']));

-- `updated_at` is written by the client on upsert, the same as the other menu
-- tables; there is no shared touch trigger in this schema to hang it on.
